In [10]:
# import pandas as pd
#
# df = pd.read_csv("data/sales.csv")
# df
# #数据清洗
# #1.处理缺失值
# df.isnull()
#删除缺失值,填充缺失值
# df.dropna()#删除了一整行
# df1 = df.dropna(axis=1)#删除了一整列
# df
# df.fillna('--')
df.ffill()# 前向填充
df.bfill()# 后向填充
# df

            订单号  产品类别  产品名称  销售数量   单价  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399  微信支付  2025-06-01
3    6823473137    食品    面包     3   29   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19  微信支付  2025/06/02
..          ...   ...   ...   ...  ...   ...         ...
995  5887473055    图书    小说    10   49  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89   银行卡  2026-03-20

[1000 rows x 7 columns]

In [15]:
#重复值处理
#查看重复值
df.duplicated()#所有的列都一样才算重复
df.duplicated(subset=['订单号'])#查看指定列重复
#删除重复值
df.drop_duplicates(subset=['订单号'],keep='last')#last保留最后一个
df.drop_duplicates(subset=['订单号'],keep='first')#first保留第一个

            订单号  产品类别  产品名称  销售数量   单价  支付方式        订单日期
0    6805677496  家居用品    枕头    10  199   支付宝  2025-06-01
1    5857234132    食品    海苔     5   29    现金  2025-06-01
2    5888085059  电子产品  智能音箱     5  399  微信支付  2025-06-01
3    6823473137    食品    面包     3   29   银行卡  2025-06-02
4    6801664364    食品    薯片     2   19  微信支付  2025/06/02
..          ...   ...   ...   ...  ...   ...         ...
995  5887473055    图书    小说    10   49  微信支付  2026-03-20
996  5808511756    食品    坚果     2   79   支付宝  2026-03-20
997  5811169466    服装    围巾     4  129   支付宝  2026-03-20
998  6876456690    食品    果汁     7   39   支付宝  2026-03-20
999  6842608338    食品    蜂蜜     5   89   银行卡  2026-03-20

[1000 rows x 7 columns]

In [19]:
#异常值处理
# df[df['单价']<0]
#
# df.drop(df[df['单价']<0].index
#         )

df['单价'] = df['单价'].abs()

C:\Users\13393\AppData\Local\Temp\ipykernel_136716\2835957053.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['单价'] = df['单价'].abs()